name: Rust Crypto CI

on: [pull_request, push]

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: markdown nits
      run: |
        sudo gem install mdl
        mdl -s markdownlint.rb README.md
